/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CanteenRouteImport } from './routes/canteen'
import { Route as LostFoundRouteImport } from './routes/lost-found'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ParkingRouteImport } from './routes/parking'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as StudyRoomsRouteImport } from './routes/study-rooms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CanteenRoute = CanteenRouteImport.update({
  id: '/canteen',
  path: '/canteen',
  getParentRoute: () => rootRouteImport,
} as any)
const LostFoundRoute = LostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingRoute = ParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoomsRoute = StudyRoomsRouteImport.update({
  id: '/study-rooms',
  path: '/study-rooms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/canteen': typeof CanteenRoute
  '/lost-found': typeof LostFoundRoute
  '/maintenance': typeof MaintenanceRoute
  '/parking': typeof ParkingRoute
  '/safety': typeof SafetyRoute
  '/study-rooms': typeof StudyRoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/canteen': typeof CanteenRoute
  '/lost-found': typeof LostFoundRoute
  '/maintenance': typeof MaintenanceRoute
  '/parking': typeof ParkingRoute
  '/safety': typeof SafetyRoute
  '/study-rooms': typeof StudyRoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/canteen': typeof CanteenRoute
  '/lost-found': typeof LostFoundRoute
  '/maintenance': typeof MaintenanceRoute
  '/parking': typeof ParkingRoute
  '/safety': typeof SafetyRoute
  '/study-rooms': typeof StudyRoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/canteen'
    | '/lost-found'
    | '/maintenance'
    | '/parking'
    | '/safety'
    | '/study-rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/canteen'
    | '/lost-found'
    | '/maintenance'
    | '/parking'
    | '/safety'
    | '/study-rooms'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/canteen'
    | '/lost-found'
    | '/maintenance'
    | '/parking'
    | '/safety'
    | '/study-rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CanteenRoute: typeof CanteenRoute
  LostFoundRoute: typeof LostFoundRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ParkingRoute: typeof ParkingRoute
  SafetyRoute: typeof SafetyRoute
  StudyRoomsRoute: typeof StudyRoomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canteen': {
      id: '/canteen'
      path: '/canteen'
      fullPath: '/canteen'
      preLoaderRoute: typeof CanteenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost-found': {
      id: '/lost-found'
      path: '/lost-found'
      fullPath: '/lost-found'
      preLoaderRoute: typeof LostFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking': {
      id: '/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof ParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-rooms': {
      id: '/study-rooms'
      path: '/study-rooms'
      fullPath: '/study-rooms'
      preLoaderRoute: typeof StudyRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CanteenRoute: CanteenRoute,
  LostFoundRoute: LostFoundRoute,
  MaintenanceRoute: MaintenanceRoute,
  ParkingRoute: ParkingRoute,
  SafetyRoute: SafetyRoute,
  StudyRoomsRoute: StudyRoomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
